##
## EPITECH PROJECT, 2023
## Makefile
## File description:
## By Thomas Baruzier
##

CC=gcc
#CFLAGS= -Wall -Wextra
#CFLAGS= -Wall -Wextra -Werror
CFLAGS= -Wall -Wextra -Werror -Ofast -march=native -flto

all: get_tasks

####################
# HIGH LEVEL TASKS #
####################

get_tasks: *.c
	@{ \
		[ -s "main.c" ] && make --no-print-directory main; \
		[ -n "$$(find tests/*.c)" ] && make --no-print-directory tests_run; \
	}

get_tasks_debug: *.c fclean
	@{ \
		[ -s "main.c" ] && make --no-print-directory debug; \
		[ -n "$$(find tests/*.c)" ] && make --no-print-directory coverage; \
	}

review: get_tasks_debug banana

live: *.c
	@echo -e '\n\e[0;1m==> INFO: Live mode activated.\e[0m'
	@{ \
		trap "echo -e '\e[?25h' && exit" 2 3 && echo -e '\e[?25l'; \
		while true; do \
			new=$$(cat $$(find -name '*.c' -o -name '*.h') | md5sum); \
			[ "$$previous" != "$$new" ] && previous="$$new" && \
			echo -en '\e[A' && make --no-print-directory get_tasks; \
			sleep 0.5; \
		done \
	}

live_debug: *.c
	@echo -e '\n\e[0;1m==> INFO: Live mode activated.\e[0m'
	@{ \
		trap "echo -e '\e[?25h' && exit" 2 3 && echo -e '\e[?25l'; \
		while true; do \
			new=$$(cat $$(find -name '*.c' -o -name '*.h') | md5sum); \
			[ "$$previous" != "$$new" ] && previous="$$new" && \
			echo -en '\e[A' && make --no-print-directory get_tasks_debug; \
			sleep 0.5; \
		done \
	}

############
# BUILDING #
############

main: *.c lib/libmy.a include/functions.h
	@echo -e '\n\e[34;1m==> TARGET: main\e[0m\n'
	$(CC) $(CFLAGS) *.c -c -I./include/
	$(CC) $(CFLAGS) *.o -o main -L./lib/ -lmy
	@echo -e '\n\e[32;1m==> SUCCESS: Built main!\e[0m\n'
	@echo -e '\e[0;1mExecuting ./main...\n\e[33m▼\e[0m'
	@make --no-print-directory exec_params
	@echo -e '\e[s\n\e[u\e[33;1m\e[B▲\e[0m\n'

debug: *.c lib/libmy.a include/functions.h
	@echo -e '\n\e[34;1m==> TARGET: debug\e[0m\n'
	$(CC) $(CFLAGS) *.c -c -I./include/
	$(CC) $(CFLAGS) *.o -o main -L./lib/ -lmy
	@echo -e '\n\e[32;1m==> SUCCESS: Built main!\e[0m\n'
	@echo -e '\e[0;1mExecuting ./main in debugging mode...\n\e[33m▼\e[0m'
	@make --no-print-directory exec_params_debug
	@echo -e '\e[s\n\e[u\e[33;1m\e[B▲\e[0m\n'

test: tests_run
tests/*.gcno: tests_run
tests/*.gcda: tests_run

tests_run: *.c tests/*.c lib/libmy.a include/functions.h
	@echo -e '\n\e[34;1m==> TARGET: tests_run\e[0m\n'
	$(CC) $(CFLAGS) $$(ls *.c | grep -v main.c) tests/*.c -o tests/unit_tests \
		-I./include/ -L./lib/ -lcriterion -lmy --coverage
	@echo -e '\n\e[32;1m==> SUCCESS: Built tests_run!\e[0m\n'
	@echo -e '\e[0;1mExecuting ./tests/unit_tests...\e[0m\n'
	@./tests/unit_tests
	@echo

#########
# LIBMY #
#########

libmy: lib/libmy.a

lib/libmy.a:
	cd lib/my && make && cd ../..

########
# EXEC #
########

exec: main
	@./main

exec_params: main
	@./main "This is an arg built into the Makefile" "second" "third"

exec_debug: main
	@./main | cat -e

exec_params_debug: main
	@./main "This is an arg built into the Makefile" "second" "third" | cat -e

##########
# HEADER #
##########

header: include/functions.h
include/functions.h:
	@{ \
		echo; \
		types='int|char|float|double|void|long|short|'; \
		types+='signed|unsigned|size_t|uint|static|const'; \
		proto=$$(grep -Ph "^($$types) [^\(]+[^\)]+\)$$" *.c); \
		header+='/*\n** EPITECH PROJECT, 2023'; \
		header+='\n** functions.h'; \
		header+='\n** File description:'; \
		header+='\n** Header file for all the functions of the '; \
		header+='current day\n** Auto-generated by Makefile\n*/'; \
		header+='\n\n#include <unistd.h>\n#include <stdlib.h>'; \
		header+='\n\n#ifndef FUNCTIONS_H\n    #define FUNCTIONS_H\n\n'; \
		header+=$$(grep -v static <<< $$proto | sort -u | sed 's/$$/;/g'); \
		header+='\n\n#endif'; \
		mkdir -p include; \
		echo -e "$$header" > include/functions.h; \
	}
	@echo -e '\e[0;1m==> Header file functions.h automatically generated\e[0m'

#################
# CODE COVERAGE #
#################

coverage: tests/*.gcno tests/*.gcda
	@echo -e '\n\e[34;1m==> TARGET: coverage\e[0m\n'
	@{ \
 		output=$$(gcovr --exclude tests | tail -n+5); \
		output=$$(head -n-3 <<< "$$output" | grep -v 100%); \
		if [ $$(wc -l <<< "$$output") -le 2 ]; then \
 		  echo -e "> \e[0;1m100% Line coverage\e[0m\n"; \
 	  else \
 		  echo -e "$$output\n"; \
 	  fi; \
 	  output=$$(gcovr --exclude tests --branches | tail -n+5); \
 	  output=$$(head -n-3 <<< "$$output" | grep -v 100%); \
 	  if [ $$(wc -l <<< "$$output") -le 2 ]; then \
 		  echo -e "> \e[0;1m100% Branch coverage\e[0m"; \
 	  else \
 		  echo "$$output"; \
 	  fi \
	}
	@echo

##########
# BANANA #
##########

banana:
	@make --no-print-directory fclean
	@{ \
		input="$$PWD"; \
		output="/home/$$USER/.cache/coding-style-checker"; \
		sudo rm -rf "$$output"; \
		mkdir -p "$$output"; \
		sudo docker run --rm -i -v "$$input":/mnt/delivery \
			-v "$$output":/mnt/reports \
			ghcr.io/epitech/coding-style-checker:latest \
			/mnt/delivery /mnt/reports; \
		export_file=$$(find "$$output" -type f | head -n 1); \
		sed -i '/illegal token in column/d' "$$export_file"; \
		if [ -f "$$export_file" ]; then \
			errors=$$(wc -l < "$$export_file"); \
			fatal=$$(grep -c 'FATAL' < "$$export_file"); \
			major=$$(grep -c 'MAJOR' < "$$export_file"); \
			minor=$$(grep -c 'MINOR' < "$$export_file"); \
			info=$$(grep -c 'INFO' < "$$export_file"); \
			if [ -s "$$export_file" ]; then \
				echo -e "\n\e[0;1m> Banana report: \e[0m\n"; \
				column < "$$export_file"; \
				echo; \
			else \
				echo -en "\n\e[0;1m> Banana report: \e[0m"; \
			fi; \
		echo -en "\e[31mFATAL: $$fatal \e[0m- \e[33mMAJOR: $$major \e[0m"; \
		echo -e "- \e[32mMINOR: $$minor \e[0m- \e[34mINFO: $$info\e[0m\n"; \
		fi; \
	}

#########
# CLEAN #
#########

re: fclean all

fclean: clean
	rm -f main tests/unit_tests lib/*/*.o lib/*/*.a lib/*.a
	rm -f lib/my/my.h include/my.h include/functions.h

clean:
	rm -f *.o */*.o */*/*.o tests/*.gcno tests/*.gcda
